name: Daily Trending Publisher

on:
  schedule:
    - cron: '5 1 * * *'  # 每日 01:05 UTC 執行
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t daily-tasks:latest .

      - name: Run container
        env:
          # LLM 供應商與金鑰（可改為 OLLAMA）
          LLM_PROVIDER: claude
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

          # GitHub 權杖與目標 Repo（預設為目前倉庫）
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO: ${{ github.repository }}
          TARGET_BRANCH: main

          # 其他參數（Python 程式內有預設值，可省略）
          MAX_REPOS: 5
          PATH_PREFIX: daily
          TIMEZONE: Asia/Taipei
          COMMIT_AUTHOR_NAME: DailyTasksBot
          COMMIT_AUTHOR_EMAIL: bot@example.com
        run: |
          docker run --rm \
            -e LLM_PROVIDER \
            -e ANTHROPIC_API_KEY \
            -e GITHUB_TOKEN \
            -e TARGET_REPO \
            -e TARGET_BRANCH \
            -e MAX_REPOS \
            -e PATH_PREFIX \
            -e TIMEZONE \
            -e COMMIT_AUTHOR_NAME \
            -e COMMIT_AUTHOR_EMAIL \
            daily-tasks:latest


